// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdUknBvTzUkHPRA5cieslBbH6fsmZdjho',
    appId: '1:590872537189:web:3084f38a4cb71d64b93e8c',
    messagingSenderId: '590872537189',
    projectId: 'flutter-firebase-crud-bd1df',
    authDomain: 'flutter-firebase-crud-bd1df.firebaseapp.com',
    storageBucket: 'flutter-firebase-crud-bd1df.appspot.com',
    measurementId: 'G-F2G6NQCKP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2wD-DTIuW_J034AYB3CrVvX6Jq18itNU',
    appId: '1:590872537189:android:fd81ad8f1e898659b93e8c',
    messagingSenderId: '590872537189',
    projectId: 'flutter-firebase-crud-bd1df',
    storageBucket: 'flutter-firebase-crud-bd1df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLIWkCA_GowaCS1yrOOfkttfd9LUpg694',
    appId: '1:590872537189:ios:f9896373cb85634eb93e8c',
    messagingSenderId: '590872537189',
    projectId: 'flutter-firebase-crud-bd1df',
    storageBucket: 'flutter-firebase-crud-bd1df.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLIWkCA_GowaCS1yrOOfkttfd9LUpg694',
    appId: '1:590872537189:ios:e399ee63a8072b53b93e8c',
    messagingSenderId: '590872537189',
    projectId: 'flutter-firebase-crud-bd1df',
    storageBucket: 'flutter-firebase-crud-bd1df.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseCrud.RunnerTests',
  );
}
